import { NORMAL_MODE } from "./constants.js";

export function createInitialState(metadata) {
  return {
    upstreamReady: false,
    generationStarted: false,
    sentFinalCommit: false,
    finalizeRequested: false,
    sawAudio: false,
    receivedFinalDone: false,
    fullTranscript: "",
    pendingAudio: [],
    seenUpstreamTypes: new Set(),
    seenControlTypes: new Set(),
    loggedNonJsonText: false,
    lastAudioProgressMark: -1,
    metadata,
    totalAudioSeconds: 0,
    words: [],
    lastWordEndSec: 0,
    finalizedWordCount: 0,
    finalizationTimer: null,
    idleKeepaliveTimer: null,
    clientResultsHeartbeatTimer: null,
    adaptiveTimer: null,
    metricsTimer: null,
    lastClientResultsAtMs: Date.now(),
    lastClientAudioAtMs: 0,
    lastChunkCommitAtMs: 0,
    chunkIdCounter: 0,
    audioSinceCommitSec: 0,
    currentMode: NORMAL_MODE,
    finalizedAudioSec: 0,
    finalizedTailNormalized: [],
    lastMetricAtMs: Date.now(),
    lastMetricFinalizedAudioSec: 0,
    recentMonoChunks: [],
    channelActivity: [],
    lastResolvedSpeaker: null,
  };
}
